# frps日志文件
frps_log: /usr/local/frp/log/frps.20260215-000000.log

# 输出日志目录
logs: /home/ubuntu/github/frptables/logs/

# frps 名字端口对应配置
name_port:
  "nas-win-rdp-tcp": 30626
  "nas-win-rdp-udp": 30626
  "tcp-pc-rdp": 30627
  "ucp-pc-rdp": 30627

# 启用防火墙类型 iptables / firewall / md (Microsoft Defender)
tables_type: iptables

# ip白名单:
allow_ip:
  - 127.0.0.1

allow_port: []

rules:
  - port: 30626
    country: ""
    regionName: ""
    city: ""
    time: 60
    count: 5
  - port: 30627
    country: ""
    regionName: ""
    city: ""
    time: 60
    count: 5
  - port: -1
    country: ""
    regionName: ""
    city: ""
    time: 60
    count: 10

ipinfo: '[{"enable":true,"name":"ipapi","url":"http://ip-api.com/json/{ip}?lang=zh-CN","field":{"country":"country","regionName":"regionName","city":"city","lat":"lat","lon":"lon"}}]'
